# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.16)
{

  description = "Web based QR code generator";


  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.2405.*";
  };


  outputs = { self, flake-schemas, nixpkgs }:
    let

      supportedSystems = [ "x86_64-linux" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });
    in {

      schemas = flake-schemas.schemas;


      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.callPackage ./shell.nix {};
        });
    };
}
